#!/bin/bash

# This script gets the current tag status from hlwm and
# renders it as a text string polybar can render

############
# Settings #
############

# Colors
# These should match, or at least complement, the colors
# in ~/.config/polybar/config currently they're dynamically set
# so they will always match

background_color=$(get-x-color background)
underline_color=$(get-x-color 3)

function foreground {
	# $1 = color
	# $2 = text
	# Formats the text so polybar renders
	# it with the provided color
    echo "%{F$1}$2 %{F-}"
}

function underline {
	# $1 = color
	# $2 = text
	# Formats the text so polybar renders
	# it underlined with the provided color
    echo "%{u$1 +u}$2 %{-u}"
}

function format {
    # $1 = status
    # $2 = tag
	# Based on the status renders the tag accordingly
    case $1 in
        ".")
            echo $(foreground $background_color $2)
            ;;
        "#")
            echo $(underline $underline_color $2)
            ;;
        *)
            echo "$2 "
            ;;
    esac
}

tags=$(herbstclient tag_status)
output=" "
for tag in $tags:
           do
               output+=" $(format ${tag:0:1} ${tag:1})"
           done

echo "$output"
