"Vim config stuff

"Colors {{{
colorscheme molokai       "  Sets the colorscheme
syntax enable             "  Enables syntax highlighting
"}}}

"Tabs {{{
set tabstop=4             "  Tabs show up as 4 spaces
set softtabstop=4         "  Number of spaces per tab
set expandtab             "  Tabs become spaces
set modelines=1
"}}}

"Ui stuff {{{
set relativenumber        "  Turns on relative line numbers
set cursorline            "  Highlight current line
set showcmd               "  Show last cmd used
set lazyredraw            "  Only draw when needed
set showmatch             "  Highlight matching brackets
"}}}

"Folds {{{
set foldenable            "  Turns on folding
set foldmethod=syntax     "  Fold based on syntax
"}}}

"Plugins {{{
execute pathogen#infect()
"}}}
" vim:foldmethod=marker:foldlevel=0
