#! /bin/bash

hc() {
	cmds="$cmds , $@"	
}

hc emit_hook recolor

# theme
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'

hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'

#outer frame
hc attr theme.active.color $(get_x_color 3)
hc attr theme.normal.color '#454545'


hc attr theme.urgent.color orange
hc attr theme.inner_color black
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $(get_x_color 5)

#No idea what this one does
hc attr theme.active.outer_color '#c0ffee'

hc attr theme.background_color '#141414'

herbstclient chain $cmds&
