#! /bin/bash

# Defines padding and all that jazz

function hc {
	cmds="$cmds , $@"
}

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 20

hc attr theme.inner_width 1
hc attr theme.border_width 5
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# padding
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
	hc pad $monitor 60
done

echo $cmds
