#! /bin/bash

hc() {
	cmds="$cmds , $@"	
}

hc emit_hook recolor

color3=$(get-x-color 3)
color5=$(get-x-color 5)

# theme
hc set frame_border_active_color $color3
hc set frame_border_normal_color $color5

hc set frame_bg_normal_color $color5
hc set frame_bg_active_color $color3

#outer frame
hc attr theme.active.color $color3
hc attr theme.normal.color $color5


hc attr theme.urgent.color orange
hc attr theme.inner_color $color5
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $color5

#No idea what this one does
hc attr theme.active.outer_color '#c0ffee'

hc attr theme.background_color '#141414'

herbstclient chain $cmds&
