#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs


if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/* ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi


# Set background
xsetroot -solid "#282828"

#Create keybindings
xbindkeys

#Start up the urxvt daemon
urxvtd -q -f -o

# Select Window Manager
#case $1 in
#ratpoison)
        #exec ratpoison
        #;;
#2bwm)
        #exec 2bwm
        #;;
#musca)
        #exec musca
        #;;
#herbs|*) 
        #exec herbstluftwm -c ~/.herbstluftwm/autostart
        #;;
#
#esac

exec herbstluftwm --lock

