#!/usr/bin/env python3
import fileinput
from subprocess import Popen,PIPE

update = ['polybar-msg',
          'hook',
          'hlwm',
          '1']


def announce_update():
    Popen(update)

if __name__=='__main__':

    for line in fileinput.input():
        print("tag status changed")
        announce_update()
