#!/usr/bin/env python3
import fileinput
from subprocess import Popen,PIPE

# Settings, these need to be set to match ~/.config/polybar/config
# If you want them to look nice at all

#Colors
background_color = "#222"
foregound_color  = "#dfdfdf"
underline_color  = "#fba922"

def foreground(color,message):
    message = message.decode("utf-8")
    output = "%{F"
    output += (color)
    output += ("} ")
    output += (message)
    output +=  "%{F-}"
    
    return output

def background(color,message):
    message = message.decode("utf-8")
    output = "%{B"
    output += (color)
    output += ("} ")
    output += (message)
    output +=  "%{B-}"
    
    return output

def underline(color,message):
    message = message.decode("utf-8")
    output = "%{u"
    output += (color)
    output += (" +u}")
    output += (message)
    output += ("%{-u}")
    return output

def get_status_format(status):
    status = chr(status)
    if status == '.':
        return lambda message: foreground(background_color,message)
    elif status == '#':
        return lambda message: underline(underline_color,message)
    else:
        return lambda x: x.decode("utf-8")

def parse_tag(tag):
    status = tag[0]
    name = tag[1:]
    formating = get_status_format(status)
    return formating(name)

def get_tags():
    p = Popen(['herbstclient', 'tag_status'],stdout=PIPE)
    tags = p.communicate()[0].split()
    return tags

if __name__=='__main__':
    output = None
    for tag in get_tags():
        if not output:
            output = parse_tag(tag)
        else:
            output += " " + parse_tag(tag)
    print(output)
