#!/bin/bash

choice=$(echo "Lock
Sleep
Hibernate
Shutdown
Reboot" | rofi -dmenu -lines 5 -width -20 -p ">>")

if [ choice == "Hibernate" ]
then
	systemctl hibernate
else
	echo "$choice not understood"
fi

