#!/bin/bash

choice=$(echo "Lock
Sleep
Hibernate
Reboot
Shutdown
Quit" | rofi -dmenu -lines 5 -width -20 -p ">>")

case "$choice" in
	Hibernate)
		systemctl hibernate
		;;

	Sleep)
		systemctl suspend
		;;

	Shutdown)
		poweroff
		;;

	Reboot)
		reboot
		;;

	Lock)
		echo "Locking not yet implemented"
		;;
	Quit)
		herbstclient quit
		;;

	*)
		echo "$choice not an option"
esac
