#!/usr/bin/env bash

# this is a simple config for herbstluftwm

~/.screenlayout/layout.sh

# Not currently using wal
#wal -s -t -n -l --theme moe

hc() {
	cmds="$cmds , $@"
}

hc emit_hook reload

hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

~/.config/herbstluftwm/scripts/rules
~/.config/herbstluftwm/scripts/keybind
~/.config/herbstluftwm/scripts/workspace
~/.config/herbstluftwm/scripts/theme

herbstclient chain $cmds&
# set-wallpaper
~/.config/herbstluftwm/scripts/colors
~/.config/herbstluftwm/polybar/panel.sh
~/.config/herbstluftwm/polybar/listen.sh &
