# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/pigpenguin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
autoload -U colors && colors
autoload -U promptinit
promptinit

prompt="%{$fg[yellow]%}|%{$reset_color%}%{$fg[green]%}%M%{$reset_color%} %{$fg[red]%}%t%{$reset_color%}%{$fg[yellow]%}|%{$reset_color%} %{$fg[cyan]%} %~ %{$reset_color%}"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source $HOME/.aliases
