"""vim config stuff

"Tabs {{{
set tabstop=4             " Tabs show up as 4 spaces
set softtabstop=4         " Number of spaces per tab
set expandtab             " Tabs become spaces
set shiftwidth=4          " Sets indent size
set modelines=1
set autoindent
"}}}

"Ui stuff {{{
set relativenumber        "  Turns on relative line numbers
set cursorline            "  Highlight current line
set showcmd               "  Show last cmd used
set lazyredraw            "  Only draw when needed
set showmatch             "  Highlight matching brackets
"}}}

"Folds {{{
set foldenable            "  Turns on folding
set foldmethod=syntax     "  Fold based on syntax
set foldcolumn=3          "  Show the folds in the left column
"}}}

"Plugins {{{
execute pathogen#infect()

let mapleader="," "Make the leader comma

"Gundo
nnoremap <leader>u :GundoToggle<CR>

"}}}

"Haskell {{{

filetype plugin on " Haskell plugins need to detect when I'm working on haskell

"Hdev {{{
au FileType haskell nnoremap <buffer> <F1> :HdevtoolsType<CR>           "Pressing f1 shows type
au FileType haskell nnoremap <buffer> <silent> <F2> :HdevtoolsClear<CR> "Pressing f2 clears
au FileType haskell nnoremap <buffer> <silent> <F3> :HdevtoolsInfo<CR>  "Pressing f3 shows info
"}}}

"Haskell Conceal{{{
let hscoptions="℘𝐒𝐓𝐄𝐌xerb↱w-iRt" " This disables most of the plugin.
                                 " All of these either render poorly or I have
                                 " no idea what the symbol means...
" }}}

" Auto Complete {{{
let g:necoghc_enable_detailed_browse = 1 "Adds type signatures to the autocomplete
let g:neocomplete#enable_at_startup  = 1 "Enable autocomplete by default
" }}}

"}}}

"Colors {{{
"  Some nice colorschemes include
"  Tomorrow-Night
"  Tomorrow-Night-Bright
"  adaryn
"  af
"  flatcolor
colorscheme Tomorrow-Night        "  Sets the colorscheme
syntax enable             "  Enables syntax highlighting
"}}}


" vim:foldmethod=marker:foldlevel=0
