#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
	cmds="$cmds , $@"
}

hc emit_hook reload

hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

herbstclient chain $cmds&
~/.config/herbstluftwm/scripts/rules
~/.config/herbstluftwm/scripts/keybind
~/.config/herbstluftwm/scripts/workspace
~/.config/herbstluftwm/scripts/theme
~/.config/herbstluftwm/scripts/colors
