#!/usr/bin/env bash

# this is a simple config for herbstluftwm

~/.screenlayout/dual_monitor.sh

hc() {
	cmds="$cmds , $@"
}

hc emit_hook reload

hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

~/.config/herbstluftwm/scripts/rules&
~/.config/herbstluftwm/scripts/keybind&
~/.config/herbstluftwm/scripts/workspace&
~/.config/herbstluftwm/scripts/theme

herbstclient chain $cmds&
~/.config/scripts/update_wallpaper
~/.config/herbstluftwm/polybar/panel.sh
