#! /bin/bash

# Takes the argument, renders it as an equation
# copies the equation to the clipboard
doc="\documentclass[border=1pt]{standalone}
\usepackage[dvipsnames]{xcolor}
\usepackage{amsmath}
\usepackage{amsfonts}
\newenvironment{mymath}{$\displaystyle}{$}
\begin{document}
{\color{PineGreen}
 \begin{mymath}
 $@
 \end{mymath}
}
\end{document}"


echo $doc | pdflatex --output-dir /tmp
convert -density 300 /tmp/standalone.pdf -quality 90 png:- | xclip -selection clipboard -t image/png

