#!/bin/bash

choice=$(echo "Lock
Sleep
Hibernate
Reboot
Shutdown
Quit" | rofi -dmenu -lines 6 -width -20 -p ">>")

function lock {
	sflock -c '|'
	sleep 3
}

function confirm {
    choice=$(echo "Yes
No" | rofi -dmenu -lines 2 -width -20 -p "$1?")

    case $choice in
        Yes)
            $2
            ;;
        *)
            echo "Not going to $1"
    esac
}

case "$choice" in
	Hibernate)
      confirm
		  lock
		  systemctl hibernate
		  ;;

	Sleep)
		  lock
		  systemctl suspend
		  ;;

	Shutdown)
		  confirm shutdown poweroff
		  ;;

	Reboot)
		  confirm reboot reboot
		  ;;

	Lock)
      lock
		  ;;
	Quit)
		  herbstclient quit
		  ;;

	*)
		  echo "$choice not an option"
esac
