#!/bin/bash

choice=$(echo "Lock
Sleep
Hibernate
Reboot
Shutdown
Quit" | rofi -dmenu -lines 6 -width -20 -p ">>")

function lock {
	sflock -c '|'
	sleep 3
}

case "$choice" in
	Hibernate)
		lock
		systemctl hibernate
		;;

	Sleep)
		lock
		systemctl suspend
		;;

	Shutdown)
		poweroff
		;;

	Reboot)
		reboot
		;;

	Lock)
		lock
		;;
	Quit)
		herbstclient quit
		;;

	*)
		echo "$choice not an option"
esac
