#!/bin/bash

choice=$(echo "Lock
Nap
Sleep
Hibernate
Reboot
Reboot-Menu
Shutdown
Quit" | rofi -dmenu -lines 8 -width -20 -p ">>")

function lock {
	light-locker-command -l
	#sflock -c '|'
	#sleep 3
}

function confirm {
    choice=$(echo "Yes
No" | rofi -dmenu -lines 2 -width -20 -p "$1?")

    case $choice in
        Yes)
            $2
            ;;
        *)
            echo "Not going to $1"
    esac
}

case "$choice" in
    Nap)
        sleep 1; xset dpms force off
        ;;
	  Hibernate)
		    lock
		    systemctl hibernate
		    ;;

	  Sleep)
		    lock
		    systemctl suspend
		    ;;

	  Shutdown)
		    confirm shutdown poweroff
		    ;;

	  Reboot)
		    confirm reboot reboot
		    ;;

          Reboot-Menu)
		    confirm reboot "systemctl reboot --boot-loader-menu=10"
		    ;;
	  Lock)
        	    lock
		    ;;
	  Quit)
		    herbstclient quit
		    ;;

	  *)
		  echo "$choice not an option"
esac
