#! /bin/bash
usage="usage: set-wallpaper monitor(1 for primary 2 for secondary) image"

# Where nitrogen is looking for files
directory=~/Images/Wallpapers

function setWallpaper {	
	# Tells nitrogen to apply the images currently linke in the wallpaper directory
	nitrogen --restore

	# Clear the wal cache
	wal -c

	# Generates a color scheme to match the wallpaper on the primary monitor
	# -q : silent, no output
	# -n : don't override the wallpaper, nitrogen handles that
	# -i : the image to use as our source
	# -a : transparency value
	# -s : don't mess with the terminal
	# -t : don't mess with the tty
	wal -s -t -n -i ~/Images/Wallpapers/1 -a "95"

	# Tells our window manager to read the new wal colors and apply them
	~/.config/herbstluftwm/scripts/colors
}

case $# in
	0)
		# If called with no argument just apply the currently saved wallpapers
		# Intended to be used on boot
		setWallpaper
		exit 0
		;;
	1)
		# If called with a single argument apply the supplied image to both monitors
		if [ ! -f "$1" ]
		then
			echo "$1 does not exist"
			exit 1
		fi
		ln -f "$1" "$directory/1"
		ln -f "$1" "$directory/2"
		setWallpaper
		exit 0
		;;
	2)
		# If called with two arguments apply the supplied image ($2) to the supplied
		# monitor ($1)
		if [ ! -f "$2" ]
		then
			echo "$2 does not exist"
			exit 1
		fi
		case $1 in
			1)
				ln -f "$2" "$directory/1"
				setWallpaper
				exit 0
				;;
			2)
				ln -f "$2" "$directory/2"
				# As all the color schemes are based on monitor 1, only cause nitrogen
				# to recheck
				nitrogen --restore
				exit 0
				;;
			*)
				echo $usage
				exit 1
				;;
		esac
		;;
	*)
		# User error
		echo $usage
		exit 1
		;;
esac





