#! /bin/bash
usage="usage: set-wallpaper monitor(1 for primary 2 for secondary) image"

# Where nitrogen is looking for files
directory=~/Images/Wallpapers

function setWallpaper {	
	# Tells nitrogen to apply the images currently linke in th wallpaper directory
	nitrogen --restore

	# Generates a color scheme to match the wallpaper on the primary monitor
	# -q : silent, no output
	# -c : clear the old colorscheme
	# -n : don't override the wallpaper, nitrogen handles that
	# -i : the image to use as our source
	# -a : transparency value
	wal -q -c -n -i ~/Images/Wallpapers/1 -a "95"

	# Tells our window manager to read the new wal colors and apply them
	~/.config/herbstluftwm/scripts/colors
}


if [ $# -eq 0 ]
then
	# If called with no argument just apply the currently saved wallpapers
	# Intended to be used on boot
	setWallpaper
	exit 0
elif [ $# -ne 2 ]
then
	echo $usage
	exit 1
fi

case $1 in
	"1")
		ln -f $2 "$directory/1"
		setWallpaper
		exit 0
		;;
	"2")
		ln -f $2 "$directory/2"
		# As all the color schemes are baed on monitor 1, only cause nitrogen
		# to recheck
		nitrogen --restore
		exit 0
		;;
	*)
		echo $usage
		exit 1
esac
